[package]
name = "process"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <michal.vaner@nic.cz>"]

[dependencies]
csv = "0.15"
regex = "0.2"
scoped-pool = "1"
serde_json = "0.9"
rustc-serialize = "0.3"
fnv = "1"
